docker:
  cpu:
    image: ${ASKCOS_REGISTRY}/context_recommender:1.0-cpu
    build: docker build -f Dockerfile -t ${ASKCOS_REGISTRY}/context_recommender:1.0-cpu .
    start: sh scripts/serve_cpu_in_docker.sh

singularity:
  cpu:
    image: context_cpu.sif
    build: singularity build -f context_cpu.sif singularity_cpu.def
    start: sh scripts/serve_cpu_in_singularity.sh

commands:
  download: sh scripts/download_trained_models.sh
  stop-docker: docker stop context_recommender; docker rm context_recommender
  stop-singularity: singularity instance stop context_recommender
